var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa={},h;for(h in f)f.hasOwnProperty(h)&&(aa[h]=f[h]);f.arguments=[];f.thisProgram="./this.program";f.quit=function(a,b){throw b;};f.preRun=[];f.postRun=[];var da=!1,ea=!1,k=!1,fa=!1;da="object"===typeof window;ea="function"===typeof importScripts;k="object"===typeof process&&"function"===typeof require&&!da&&!ea;fa=!da&&!k&&!ea;var m="";function ha(a){return f.locateFile?f.locateFile(a,m):m+a}
if(k){m=__dirname+"/";var ia,ja;f.read=function(a,b){ia||(ia=require("fs"));ja||(ja=require("path"));a=ja.normalize(a);a=ia.readFileSync(a);return b?a:a.toString()};f.readBinary=function(a){a=f.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(f.thisProgram=process.argv[1].replace(/\\/g,"/"));f.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=f);process.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;});process.on("unhandledRejection",
function(){process.exit(1)});f.quit=function(a){process.exit(a)};f.inspect=function(){return"[Emscripten Module object]"}}else if(fa)"undefined"!=typeof read&&(f.read=function(a){return read(a)}),f.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?f.arguments=scriptArgs:"undefined"!=typeof arguments&&(f.arguments=arguments),"function"===typeof quit&&(f.quit=function(a){quit(a)});
else if(da||ea)da?document.currentScript&&(m=document.currentScript.src):m=self.location.href,m=0!==m.indexOf("blob:")?m.substr(0,m.lastIndexOf("/")+1):"",f.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ea&&(f.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),f.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";
d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},f.setWindowTitle=function(a){document.title=a};var la=f.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),q=f.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||la);for(h in aa)aa.hasOwnProperty(h)&&(f[h]=aa[h]);aa=void 0;function ma(a){var b=r;r=r+a+15&-16;return b}
function na(a){var b=t[u>>2];a=b+a+15&-16;t[u>>2]=a;if(a=a>=v)oa(),a=!0;return a?(t[u>>2]=b,0):b}function pa(a){var b;b||(b=16);return Math.ceil(a/b)*b}var qa={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},ra=!1;function assert(a,b){a||x("Assertion failed: "+b)}
function sa(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;b=4==b?e:["function"===typeof ta?ta:ma,ua,ma,na][void 0===b?2:b](Math.max(d,1));if(c){var e=b;assert(0==(b&3));for(a=b+(d&-4);e<a;e+=4)t[e>>2]=0;for(a=b+d;e<a;)y[e++>>0]=0;return b}a.subarray||a.slice?B.set(a,b):B.set(new Uint8Array(a),b);return b}
function va(a){var b;if(0===b||!a)return"";for(var c=0,d,e=0;;){d=B[a+e>>0];c|=d;if(0==d&&!b)break;e++;if(b&&e==b)break}b||(b=e);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,B.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return wa(B,a)}var xa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function wa(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&xa)return xa.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var e=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|e);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|e<<6|g;else{var l=a[b++]&63;if(240==(d&248))d=(d&7)<<18|e<<12|g<<6|l;else{var n=a[b++]&63;if(248==(d&252))d=(d&3)<<24|e<<18|g<<12|l<<6|n;else{var p=a[b++]&63;d=(d&1)<<30|e<<24|g<<18|l<<12|n<<6|p}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function ya(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var n=a.charCodeAt(++g);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(2097151>=l){if(c+3>=d)break;b[c++]=240|l>>18}else{if(67108863>=l){if(c+4>=d)break;b[c++]=248|l>>24}else{if(c+5>=d)break;b[c++]=252|l>>30;b[c++]=128|l>>24&63}b[c++]=128|l>>18&63}b[c++]=
128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}function za(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Aa(a){var b=za(a)+1,c=ua(b);ya(a,y,c,b);return c}var buffer,y,B,Ba,t;
function Ca(){f.HEAP8=y=new Int8Array(buffer);f.HEAP16=Ba=new Int16Array(buffer);f.HEAP32=t=new Int32Array(buffer);f.HEAPU8=B=new Uint8Array(buffer);f.HEAPU16=new Uint16Array(buffer);f.HEAPU32=new Uint32Array(buffer);f.HEAPF32=new Float32Array(buffer);f.HEAPF64=new Float64Array(buffer)}var Da,r,Ea,Fa,Ga,Ha,Ia,u;Da=r=Fa=Ga=Ha=Ia=u=0;Ea=!1;
function oa(){x("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+v+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ja=f.TOTAL_STACK||5242880,v=f.TOTAL_MEMORY||16777216;v<Ja&&q("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+v+"! (TOTAL_STACK="+Ja+")");
f.buffer?buffer=f.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(f.wasmMemory=new WebAssembly.Memory({initial:v/65536,maximum:v/65536}),buffer=f.wasmMemory.buffer):buffer=new ArrayBuffer(v),f.buffer=buffer);Ca();function Ka(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Ia;"number"===typeof c?void 0===b.ba?f.dynCall_v(c):f.dynCall_vi(c,b.ba):c(void 0===b.ba?null:b.ba)}}}var La=[],Ma=[],Na=[],Oa=[],Pa=[],Qa=!1;
function Ta(){var a=f.preRun.shift();La.unshift(a)}var Ua=0,Va=null,Wa=null;f.preloadedImages={};f.preloadedAudios={};function Xa(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(f.wasmBinary)return new Uint8Array(f.wasmBinary);if(f.readBinary)return f.readBinary(e);throw"both async and sync fetching of the wasm failed";}catch(C){x(C)}}function b(){return f.wasmBinary||!da&&!ea||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(e,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+e+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){n=a.exports;
if(n.memory){a=n.memory;var b=f.buffer;a.byteLength<b.byteLength&&q("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);f.buffer=buffer=a;Ca()}f.asm=n;f.usingWasm=!0;Ua--;f.monitorRunDependencies&&f.monitorRunDependencies(Ua);0==Ua&&(null!==Va&&(clearInterval(Va),Va=null),Wa&&(a=Wa,Wa=null,a()))}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,l)}).then(a).catch(function(a){q("failed to asynchronously prepare wasm: "+
a);x(a)})}if("object"!==typeof WebAssembly)return q("no native wasm support detected"),!1;if(!(f.wasmMemory instanceof WebAssembly.Memory))return q("no native wasm Memory in use"),!1;a.memory=f.wasmMemory;l.global={NaN:NaN,Infinity:Infinity};l["global.Math"]=Math;l.env=a;Ua++;f.monitorRunDependencies&&f.monitorRunDependencies(Ua);if(f.instantiateWasm)try{return f.instantiateWasm(l,c)}catch(ba){return q("Module.instantiateWasm callback failed with error: "+ba),!1}f.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
Xa(e)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(e,{credentials:"same-origin"}),l).then(d).catch(function(a){q("wasm streaming compile failed: "+a);q("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="program.wast",e="program.wasm",g="program.temp.asm.js";Xa(d)||(d=ha(d));Xa(e)||(e=ha(e));Xa(g)||(g=ha(g));var l={global:null,env:null,asm2wasm:qa,parent:f},n=null;f.asmPreload=f.asm;var p=f.reallocBuffer;f.reallocBuffer=function(a){if("asmjs"===w)var b=p(a);
else a:{var c=f.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=f.buffer.byteLength;if(f.usingWasm)try{b=-1!==f.wasmMemory.grow((a-c)/65536)?f.buffer=f.wasmMemory.buffer:null;break a}catch(V){b=null;break a}b=void 0}return b};var w="";f.asm=function(a,b){if(!b.table){a=f.wasmTableSize;void 0===a&&(a=1024);var d=f.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,
element:"anyfunc"}):Array(a);f.wasmTable=b.table}b.memoryBase||(b.memoryBase=f.STATIC_BASE);b.tableBase||(b.tableBase=0);b=c(b);assert(b,"no binaryen method succeeded.");return b}})();Da=1024;r=Da+104528;Ma.push({Ia:function(){Ya()}});f.STATIC_BASE=Da;f.STATIC_BUMP=104528;r+=16;var D={};
function Za(a){if(Za.B){var b=t[a>>2];var c=t[b>>2]}else Za.B=!0,D.USER=D.LOGNAME="web_user",D.PATH="/",D.PWD="/",D.HOME="/home/web_user",D.LANG="C.UTF-8",D._=f.thisProgram,c=Ea?Qa?ta(1024):na(1024):ma(1024),b=Ea?Qa?ta(256):na(256):ma(256),t[b>>2]=c,t[a>>2]=b;a=[];var d=0,e;for(e in D)if("string"===typeof D[e]){var g=e+"="+D[e];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=g=a[e];for(var l=c,n=0;n<d.length;++n)y[l++>>0]=d.charCodeAt(n);
y[l>>0]=0;t[b+4*e>>2]=c;c+=g.length+1}t[b+4*a.length>>2]=0}
var E={F:1,A:2,yc:3,wb:4,T:5,ia:6,Ra:7,Aa:8,D:9,wa:10,S:11,Ic:11,Ba:12,Y:13,ya:14,ec:15,K:16,ha:17,Da:18,$:19,U:20,N:21,g:22,Pb:23,za:24,H:25,Fc:26,qb:27,ac:28,V:29,vc:30,Ib:31,pc:32,nb:33,Ca:34,Xb:42,tb:43,fb:44,zb:45,Ab:46,Bb:47,Hb:48,Gc:49,Sb:50,yb:51,kb:35,Ub:37,Xa:52,$a:53,Jc:54,Qb:55,ab:56,bb:57,lb:35,cb:59,cc:60,Tb:61,Cc:62,bc:63,Yb:64,Zb:65,uc:66,Vb:67,Ua:68,zc:69,gb:70,qc:71,Kb:72,ob:73,Za:74,kc:76,Ya:77,tc:78,Cb:79,Db:80,Gb:81,Fb:82,Eb:83,dc:38,aa:39,Lb:36,Z:40,lc:95,oc:96,jb:104,Rb:105,
Va:97,sc:91,ic:88,$b:92,wc:108,ib:111,Sa:98,hb:103,Ob:101,Mb:100,Dc:110,rb:112,sb:113,vb:115,Wa:114,mb:89,Jb:90,rc:93,xc:94,Ta:99,Nb:102,xb:106,fc:107,Ec:109,Hc:87,pb:122,Ac:116,jc:95,Wb:123,ub:84,mc:75,eb:125,hc:131,nc:130,Bc:86},$a={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function ab(a){f.___errno_location&&(t[f.___errno_location()>>2]=a);return a}
function bb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function cb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=bb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function db(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function eb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function fb(){var a=Array.prototype.slice.call(arguments,0);return cb(a.join("/"))}function gb(a,b){return cb(a+"/"+b)}
function hb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=bb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}
function ib(a,b){function c(a){for(var b=0;b<a.length&&""===a[b];b++);for(var c=a.length-1;0<=c&&""===a[c];c--);return b>c?[]:a.slice(b,c-b+1)}a=hb(a).substr(1);b=hb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")}var jb=[];function kb(a,b){jb[a]={input:[],output:[],M:b};lb(a,mb)}
var mb={open:function(a){var b=jb[a.node.rdev];if(!b)throw new F(E.$);a.tty=b;a.seekable=!1},close:function(a){a.tty.M.flush(a.tty)},flush:function(a){a.tty.M.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.M.qa)throw new F(E.ia);for(var e=0,g=0;g<d;g++){try{var l=a.tty.M.qa(a.tty)}catch(n){throw new F(E.T);}if(void 0===l&&0===e)throw new F(E.S);if(null===l||void 0===l)break;e++;b[c+g]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.M.fa)throw new F(E.ia);
for(var e=0;e<d;e++)try{a.tty.M.fa(a.tty,b[c+e])}catch(g){throw new F(E.T);}d&&(a.node.timestamp=Date.now());return e}},ob={qa:function(a){if(!a.input.length){var b=null;if(k){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{e=fs.openSync("/dev/stdin","r"),g=!0}catch(l){}}try{d=fs.readSync(e,c,0,256,null)}catch(l){if(-1!=l.toString().indexOf("EOF"))d=0;else throw l;}g&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=nb(b,!0)}return a.input.shift()},fa:function(a,b){null===b||10===b?(la(wa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(la(wa(a.output,0)),a.output=[])}},pb={fa:function(a,b){null===b||10===b?(q(wa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(q(wa(a.output,0)),a.output=[])}},G={C:null,l:function(){return G.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(E.F);G.C||(G.C={dir:{node:{u:G.c.u,m:G.c.m,lookup:G.c.lookup,O:G.c.O,rename:G.c.rename,unlink:G.c.unlink,rmdir:G.c.rmdir,readdir:G.c.readdir,symlink:G.c.symlink},stream:{G:G.f.G}},file:{node:{u:G.c.u,m:G.c.m},stream:{G:G.f.G,read:G.f.read,write:G.f.write,ja:G.f.ja,sa:G.f.sa,ua:G.f.ua}},link:{node:{u:G.c.u,m:G.c.m,
readlink:G.c.readlink},stream:{}},la:{node:{u:G.c.u,m:G.c.m},stream:qb}});c=rb(a,b,c,d);H(c.mode)?(c.c=G.C.dir.node,c.f=G.C.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=G.C.file.node,c.f=G.C.file.stream,c.i=0,c.b=null):40960===(c.mode&61440)?(c.c=G.C.link.node,c.f=G.C.link.stream):8192===(c.mode&61440)&&(c.c=G.C.la.node,c.f=G.C.la.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Ja:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.i;++c)b.push(a.b[c]);return b}return a.b},Lc:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.i):new Uint8Array(a.b):new Uint8Array},ma:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=G.Ja(a),a.i=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.i&&a.b.set(c.subarray(0,a.i),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Ma:function(a,b){if(a.i!=b)if(0==b)a.b=null,a.i=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.i)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.i=b}},c:{u:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;H(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.i:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.I=4096;b.blocks=Math.ceil(b.size/b.I);return b},
m:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&G.Ma(a,b.size)},lookup:function(){throw sb[E.A];},O:function(a,b,c,d){return G.createNode(a,b,c,d)},rename:function(a,b,c){if(H(a.mode)){try{var d=I(b,c)}catch(g){}if(d)for(var e in d.b)throw new F(E.aa);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=I(a,b),d;for(d in c.b)throw new F(E.aa);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new F(E.g);return a.link}},f:{read:function(a,b,c,d,e){var g=a.node.b;if(e>=a.node.i)return 0;a=Math.min(a.node.i-e,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.i=d;if(0===a.i&&0===e)return a.b=new Uint8Array(b.subarray(c,c+d)),a.i=d;if(e+d<=a.i)return a.b.set(b.subarray(c,c+d),e),d}G.ma(a,e+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.b[e+g]=b[c+g];a.i=Math.max(a.i,e+d);return d},G:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.i);if(0>b)throw new F(E.g);return b},ja:function(a,b,c){G.ma(a.node,b+c);a.node.i=Math.max(a.node.i,
b+c)},sa:function(a,b,c,d,e,g,l){if(32768!==(a.node.mode&61440))throw new F(E.$);c=a.node.b;if(l&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.i)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=ta(d);if(!d)throw new F(E.Ba);b.set(c,d)}else a=!1,d=c.byteOffset;return{Mc:d,Kc:a}},ua:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(E.$);if(e&2)return 0;G.f.write(a,b,0,d,c,!1);return 0}}},K={X:!1,Oa:function(){K.X=!!process.platform.match(/^win/);var a=
process.binding("constants");a.fs&&(a=a.fs);K.na={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ka:function(a){return Buffer.B?Buffer.from(a):new Buffer(a)},l:function(a){assert(k);return K.createNode(null,"/",K.pa(a.ea.root),0)},createNode:function(a,b,c){if(!H(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new F(E.g);a=rb(a,b,c);a.c=K.c;a.f=K.f;return a},pa:function(a){try{var b=fs.lstatSync(a);K.X&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;
throw new F(E[c.code]);}return b.mode},o:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.l.ea.root);b.reverse();return fb.apply(null,b)},Ha:function(a){a&=-2656257;var b=0,c;for(c in K.na)a&c&&(b|=K.na[c],a^=c);if(a)throw new F(E.g);return b},c:{u:function(a){a=K.o(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new F(E[c.code]);}K.X&&!b.I&&(b.I=4096);K.X&&!b.blocks&&(b.blocks=(b.size+b.I-1)/b.I|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,
gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,I:b.I,blocks:b.blocks}},m:function(a,b){var c=K.o(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new F(E[d.code]);}},lookup:function(a,b){var c=gb(K.o(a),b);c=K.pa(c);return K.createNode(a,b,c)},O:function(a,b,c,d){a=K.createNode(a,b,c,d);b=K.o(a);try{H(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;
throw new F(E[e.code]);}return a},rename:function(a,b,c){a=K.o(a);b=gb(K.o(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new F(E[d.code]);}},unlink:function(a,b){a=gb(K.o(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new F(E[c.code]);}},rmdir:function(a,b){a=gb(K.o(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new F(E[c.code]);}},readdir:function(a){a=K.o(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new F(E[b.code]);}},symlink:function(a,
b,c){a=gb(K.o(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new F(E[d.code]);}},readlink:function(a){var b=K.o(a);try{return b=fs.readlinkSync(b),b=tb.relative(tb.resolve(a.l.ea.root),b)}catch(c){if(!c.code)throw c;throw new F(E[c.code]);}}},f:{open:function(a){var b=K.o(a.node);try{32768===(a.node.mode&61440)&&(a.R=fs.openSync(b,K.Ha(a.flags)))}catch(c){if(!c.code)throw c;throw new F(E[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.R&&fs.closeSync(a.R)}catch(b){if(!b.code)throw b;
throw new F(E[b.code]);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.R,K.ka(b.buffer),c,d,e)}catch(g){throw new F(E[g.code]);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.R,K.ka(b.buffer),c,d,e)}catch(g){throw new F(E[g.code]);}},G:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.R).size}catch(d){throw new F(E[d.code]);}if(0>b)throw new F(E.g);return b}}};r+=16;r+=16;r+=16;
var ub=null,vb={},L=[],wb=1,M=null,xb=!0,N={},F=null,sb={};
function O(a,b){a=hb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={oa:!0,ga:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ga)throw new F(E.Z);a=bb(a.split("/").filter(function(a){return!!a}),!1);var e=ub;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=I(e,a[d]);c=gb(c,a[d]);e.J&&(!g||g&&b.oa)&&(e=e.J.root);if(!g||b.W)for(g=0;40960===(e.mode&61440);)if(e=zb(c),c=hb(db(c),e),e=O(c,{ga:b.ga}).node,40<g++)throw new F(E.Z);}return{path:c,node:e}}
function Ab(a){for(var b;;){if(a===a.parent)return a=a.l.ta,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Bb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%M.length}function Cb(a){var b=Bb(a.parent.id,a.name);a.L=M[b];M[b]=a}function Db(a){var b=Bb(a.parent.id,a.name);if(M[b]===a)M[b]=a.L;else for(b=M[b];b;){if(b.L===a){b.L=a.L;break}b=b.L}}
function I(a,b){var c;if(c=(c=Eb(a,"x"))?c:a.c.lookup?0:E.Y)throw new F(c,a);for(c=M[Bb(a.id,b)];c;c=c.L){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function rb(a,b,c,d){Fb||(Fb=function(a,b,c,d){a||(a=this);this.parent=a;this.l=a.l;this.J=null;this.id=wb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},Fb.prototype={},Object.defineProperties(Fb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Fb(a,b,c,d);Cb(a);return a}function H(a){return 16384===(a&61440)}
var Gb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Hb(a){var b=Gb[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b}function Ib(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Eb(a,b){if(xb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return E.Y}else return E.Y;return 0}
function Jb(a,b){try{return I(a,b),E.ha}catch(c){}return Eb(a,"wx")}function Kb(a,b,c){try{var d=I(a,b)}catch(e){return e.h}if(a=Eb(a,"wx"))return a;if(c){if(!H(d.mode))return E.U;if(d===d.parent||"/"===Ab(d))return E.K}else if(H(d.mode))return E.N;return 0}function Lb(a,b){b=b||4096;for(a=a||0;a<=b;a++)if(!L[a])return a;throw new F(E.za);}
function Mb(a,b,c){Nb||(Nb=function(){},Nb.prototype={},Object.defineProperties(Nb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var d=new Nb,e;for(e in a)d[e]=a[e];a=d;b=Lb(b,c);a.fd=b;return L[b]=a}var qb={open:function(a){a.f=vb[a.node.rdev].f;a.f.open&&a.f.open(a)},G:function(){throw new F(E.V);}};function lb(a,b){vb[a]={f:b}}
function Ob(a,b){var c="/"===b,d=!b;if(c&&ub)throw new F(E.K);if(!c&&!d){var e=O(b,{oa:!1});b=e.path;e=e.node;if(e.J)throw new F(E.K);if(!H(e.mode))throw new F(E.U);}b={type:a,ea:{},ta:b,Ka:[]};a=a.l(b);a.l=b;b.root=a;c?ub=a:e&&(e.J=b,e.l&&e.l.Ka.push(b));return a}function Pb(a,b,c){var d=O(a,{parent:!0}).node;a=eb(a);if(!a||"."===a||".."===a)throw new F(E.g);var e=Jb(d,a);if(e)throw new F(e);if(!d.c.O)throw new F(E.F);return d.c.O(d,a,b,c)}function Q(a){Pb(a,16895,0)}
function Qb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Pb(a,b|8192,c)}function Rb(a,b){if(!hb(a))throw new F(E.A);var c=O(b,{parent:!0}).node;if(!c)throw new F(E.A);b=eb(b);var d=Jb(c,b);if(d)throw new F(d);if(!c.c.symlink)throw new F(E.F);c.c.symlink(c,b,a)}function zb(a){a=O(a).node;if(!a)throw new F(E.A);if(!a.c.readlink)throw new F(E.g);return hb(Ab(a.parent),a.c.readlink(a))}function Sb(a,b){a=O(a,{W:!b}).node;if(!a)throw new F(E.A);if(!a.c.u)throw new F(E.F);return a.c.u(a)}
function Tb(a){return Sb(a,!0)}
function Ub(a,b,c,d,e){if(""===a)throw new F(E.A);b="string"===typeof b?Hb(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=cb(a);try{g=O(a,{W:!(b&131072)}).node}catch(w){}}var l=!1;if(b&64)if(g){if(b&128)throw new F(E.ha);}else g=Pb(a,c,0),l=!0;if(!g)throw new F(E.A);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!H(g.mode))throw new F(E.U);if(!l){var n=g?40960===(g.mode&61440)?E.Z:H(g.mode)&&("r"!==Ib(b)||b&512)?E.N:Eb(g,Ib(b)):E.A;if(n)throw new F(n);
}if(b&512){c=g;var p;"string"===typeof c?p=O(c,{W:!0}).node:p=c;if(!p.c.m)throw new F(E.F);if(H(p.mode))throw new F(E.N);if(32768!==(p.mode&61440))throw new F(E.g);if(c=Eb(p,"w"))throw new F(c);p.c.m(p,{size:0,timestamp:Date.now()})}b&=-641;d=Mb({node:g,path:Ab(g),flags:b,seekable:!0,position:0,f:g.f,Pa:[],error:!1},d,e);d.f.open&&d.f.open(d);!f.logReadFiles||b&1||(Vb||(Vb={}),a in Vb||(Vb[a]=1,n("read file: "+a)));try{N.onOpenFile&&(n=0,1!==(b&2097155)&&(n|=1),0!==(b&2097155)&&(n|=2),N.onOpenFile(a,
n))}catch(w){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+w.message)}return d}function Wb(a){if(null===a.fd)throw new F(E.D);a.da&&(a.da=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{L[a.fd]=null}a.fd=null}function Xb(a,b,c){if(null===a.fd)throw new F(E.D);if(!a.seekable||!a.f.G)throw new F(E.V);a.position=a.f.G(a,b,c);a.Pa=[]}
function Yb(a,b,c,d){var e=y;if(0>c||0>d)throw new F(E.g);if(null===a.fd)throw new F(E.D);if(1===(a.flags&2097155))throw new F(E.D);if(H(a.node.mode))throw new F(E.N);if(!a.f.read)throw new F(E.g);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new F(E.V);b=a.f.read(a,e,b,c,d);g||(a.position+=b);return b}
function Zb(a,b,c,d){var e=y;if(0>c||0>d)throw new F(E.g);if(null===a.fd)throw new F(E.D);if(0===(a.flags&2097155))throw new F(E.D);if(H(a.node.mode))throw new F(E.N);if(!a.f.write)throw new F(E.g);a.flags&1024&&Xb(a,0,2);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new F(E.V);b=a.f.write(a,e,b,c,d,void 0);g||(a.position+=b);try{if(a.path&&N.onWriteToFile)N.onWriteToFile(a.path)}catch(l){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+
l.message)}return b}function $b(){F||(F=function(a,b){this.node=b;this.Na=function(a){this.h=a;for(var b in E)if(E[b]===a){this.code=b;break}};this.Na(a);this.message=$a[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},F.prototype=Error(),F.prototype.constructor=F,[E.A].forEach(function(a){sb[a]=new F(a);sb[a].stack="<generic error, no stack>"}))}var ac;function bc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function cc(a,b,c){a=gb("/dev",a);var d=bc(!!b,!!c);dc||(dc=64);var e=dc++<<8|0;lb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var g=0,l=0;l<e;l++){try{var n=b()}catch(ca){throw new F(E.T);}if(void 0===n&&0===g)throw new F(E.S);if(null===n||void 0===n)break;g++;c[d+l]=n}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,e){for(var g=0;g<e;g++)try{c(b[d+g])}catch(C){throw new F(E.T);}e&&(a.node.timestamp=Date.now());
return g}});Qb(a,d,e)}var dc,FS={},Fb,Nb,Vb,ec=511;
function fc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&cb(b)!==cb(Ab(e.node)))return-E.U;throw e;}t[c>>2]=d.dev;t[c+4>>2]=0;t[c+8>>2]=d.ino;t[c+12>>2]=d.mode;t[c+16>>2]=d.nlink;t[c+20>>2]=d.uid;t[c+24>>2]=d.gid;t[c+28>>2]=d.rdev;t[c+32>>2]=0;t[c+36>>2]=d.size;t[c+40>>2]=4096;t[c+44>>2]=d.blocks;t[c+48>>2]=d.atime.getTime()/1E3|0;t[c+52>>2]=0;t[c+56>>2]=d.mtime.getTime()/1E3|0;t[c+60>>2]=0;t[c+64>>2]=d.ctime.getTime()/1E3|0;t[c+68>>2]=0;t[c+72>>2]=d.ino;return 0}var R=0;
function S(){R+=4;return t[R-4>>2]}function T(){return va(S())}function W(){var a=L[S()];if(!a)throw new F(E.D);return a}
var X={s:8192,l:function(){return rb(null,"/",16895,0)},Ga:function(){var a={j:[]};a.j.push({buffer:new Uint8Array(X.s),offset:0,v:0});var b=X.P(),c=X.P(),d=rb(X.root,b,4096,0),e=rb(X.root,c,4096,0);d.pipe=a;e.pipe=a;a=Mb({path:b,node:d,flags:Hb("r"),seekable:!1,f:X.f});d.stream=a;c=Mb({path:c,node:e,flags:Hb("w"),seekable:!1,f:X.f});e.stream=c;return{La:a.fd,Qa:c.fd}},f:{va:function(a){var b=a.node.pipe;if(1===(a.flags&2097155))return 260;if(0<b.j.length)for(a=0;a<b.j.length;a++){var c=b.j[a];if(0<
c.offset-c.v)return 65}return 0},ra:function(){return E.g},read:function(a,b,c,d){a=a.node.pipe;for(var e=0,g=0;g<a.j.length;g++){var l=a.j[g];e+=l.offset-l.v}assert(b instanceof ArrayBuffer||ArrayBuffer.isView(b));b=b.subarray(c,c+d);if(0>=d)return 0;if(0==e)throw new F(E.S);c=d=Math.min(e,d);for(g=e=0;g<a.j.length;g++){l=a.j[g];var n=l.offset-l.v;if(d<=n){var p=l.buffer.subarray(l.v,l.offset);d<n?(p=p.subarray(0,d),l.v+=d):e++;b.set(p);break}else p=l.buffer.subarray(l.v,l.offset),b.set(p),b=b.subarray(p.byteLength),
d-=p.byteLength,e++}e&&e==a.j.length&&(e--,a.j[e].offset=0,a.j[e].v=0);a.j.splice(0,e);return c},write:function(a,b,c,d){a=a.node.pipe;assert(b instanceof ArrayBuffer||ArrayBuffer.isView(b));b=b.subarray(c,c+d);c=b.byteLength;if(0>=c)return 0;0==a.j.length?(d={buffer:new Uint8Array(X.s),offset:0,v:0},a.j.push(d)):d=a.j[a.j.length-1];assert(d.offset<=X.s);var e=X.s-d.offset;if(e>=c)return d.buffer.set(b,d.offset),d.offset+=c,c;0<e&&(d.buffer.set(b.subarray(0,e),d.offset),d.offset+=e,b=b.subarray(e,
b.byteLength));d=b.byteLength/X.s|0;e=b.byteLength%X.s;for(var g=0;g<d;g++){var l={buffer:new Uint8Array(X.s),offset:X.s,v:0};a.j.push(l);l.buffer.set(b.subarray(0,X.s));b=b.subarray(X.s,b.byteLength)}0<e&&(l={buffer:new Uint8Array(X.s),offset:b.byteLength,v:0},a.j.push(l),l.buffer.set(b));return c},close:function(a){a.node.pipe.j=null}},P:function(){X.P.current||(X.P.current=0);return"pipe["+X.P.current++ +"]"}};function hc(a,b){f.setThrew(a,b||1);throw"longjmp";}
function ic(a){if(0===a)return 0;a=va(a);if(!D.hasOwnProperty(a))return 0;ic.B&&jc(ic.B);a=D[a];var b=za(a)+1,c=ta(b);c&&ya(a,y,c,b);ic.B=c;return ic.B}var kc=sa(nb("GMT"),2);function lc(a){return Math.log(a)/Math.LN10}function mc(a){return Math.log(a)/Math.LN2}
function nc(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!oc){oc=!0;t[pc()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);t[qc()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),e=a(c);d=sa(nb(d),0);e=sa(nb(e),0);c.getTimezoneOffset()<b.getTimezoneOffset()?(t[rc()>>2]=d,t[rc()+4>>2]=e):(t[rc()>>2]=e,t[rc()+4>>2]=d)}}var oc,sc={},tc=1;function uc(a,b){uc.B||(uc.B={});a in uc.B||(f.dynCall_v(b),uc.B[a]=1)}
function vc(){ab(E.wa);return-1}$b();M=Array(4096);Ob(G,"/");Q("/tmp");Q("/home");Q("/home/web_user");
(function(){Q("/dev");lb(259,{read:function(){return 0},write:function(a,b,e,g){return g}});Qb("/dev/null",259);kb(1280,ob);kb(1536,pb);Qb("/dev/tty",1280);Qb("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else b=k?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};cc("random",b);cc("urandom",b);Q("/dev/shm");Q("/dev/shm/tmp")})();Q("/proc");Q("/proc/self");Q("/proc/self/fd");
Ob({l:function(){var a=rb("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=L[+c];if(!b)throw new F(E.D);a={parent:null,l:{ta:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Ma.unshift(function(){if(!f.noFSInit&&!ac){assert(!ac,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");ac=!0;$b();f.stdin=f.stdin;f.stdout=f.stdout;f.stderr=f.stderr;f.stdin?cc("stdin",f.stdin):Rb("/dev/tty","/dev/stdin");f.stdout?cc("stdout",null,f.stdout):Rb("/dev/tty","/dev/stdout");f.stderr?cc("stderr",null,f.stderr):Rb("/dev/tty1","/dev/stderr");var a=Ub("/dev/stdin",
"r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=Ub("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=Ub("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Na.push(function(){xb=!1});Oa.push(function(){ac=!1;var a=f._fflush;a&&a(0);for(a=0;a<L.length;a++){var b=L[a];b&&Wb(b)}});Ma.unshift(function(){});Oa.push(function(){});if(k){var fs=require("fs"),tb=require("path");K.Oa()}Ma.push(function(){X.root=Ob(X,null)});u=ma(4);Fa=Ga=pa(r);
Ha=Fa+Ja;Ia=pa(Ha);t[u>>2]=Ia;Ea=!0;function nb(a,b){var c=Array(za(a)+1);a=ya(a,c,0,c.length);b&&(c.length=a);return c}f.wasmTableSize=678;f.wasmMaxTableSize=678;f.Ea={};
f.Fa={abort:x,enlargeMemory:function(){oa()},getTotalMemory:function(){return v},abortOnCannotGrowMemory:oa,invoke_ii:function(a,b){var c=Y();try{return f.dynCall_ii(a,b)}catch(d){Z(c);if("number"!==typeof d&&"longjmp"!==d)throw d;f.setThrew(1,0)}},invoke_iii:function(a,b,c){var d=Y();try{return f.dynCall_iii(a,b,c)}catch(e){Z(d);if("number"!==typeof e&&"longjmp"!==e)throw e;f.setThrew(1,0)}},invoke_iiii:function(a,b,c,d){var e=Y();try{return f.dynCall_iiii(a,b,c,d)}catch(g){Z(e);if("number"!==typeof g&&
"longjmp"!==g)throw g;f.setThrew(1,0)}},invoke_iiiii:function(a,b,c,d,e){var g=Y();try{return f.dynCall_iiiii(a,b,c,d,e)}catch(l){Z(g);if("number"!==typeof l&&"longjmp"!==l)throw l;f.setThrew(1,0)}},invoke_vi:function(a,b){var c=Y();try{f.dynCall_vi(a,b)}catch(d){Z(c);if("number"!==typeof d&&"longjmp"!==d)throw d;f.setThrew(1,0)}},invoke_vii:function(a,b,c){var d=Y();try{f.dynCall_vii(a,b,c)}catch(e){Z(d);if("number"!==typeof e&&"longjmp"!==e)throw e;f.setThrew(1,0)}},invoke_viii:function(a,b,c,d){var e=
Y();try{f.dynCall_viii(a,b,c,d)}catch(g){Z(e);if("number"!==typeof g&&"longjmp"!==g)throw g;f.setThrew(1,0)}},invoke_viiii:function(a,b,c,d,e){var g=Y();try{f.dynCall_viiii(a,b,c,d,e)}catch(l){Z(g);if("number"!==typeof l&&"longjmp"!==l)throw l;f.setThrew(1,0)}},invoke_viiiii:function(a,b,c,d,e,g){var l=Y();try{f.dynCall_viiiii(a,b,c,d,e,g)}catch(n){Z(l);if("number"!==typeof n&&"longjmp"!==n)throw n;f.setThrew(1,0)}},invoke_viiiiii:function(a,b,c,d,e,g,l){var n=Y();try{f.dynCall_viiiiii(a,b,c,d,e,
g,l)}catch(p){Z(n);if("number"!==typeof p&&"longjmp"!==p)throw p;f.setThrew(1,0)}},invoke_viiiiiii:function(a,b,c,d,e,g,l,n){var p=Y();try{f.dynCall_viiiiiii(a,b,c,d,e,g,l,n)}catch(w){Z(p);if("number"!==typeof w&&"longjmp"!==w)throw w;f.setThrew(1,0)}},___buildEnvironment:Za,___lock:function(){},___setErrNo:ab,___syscall10:function(a,b){R=b;try{var c=T(),d=O(c,{parent:!0}).node,e=eb(c),g=I(d,e),l=Kb(d,e,!1);if(l)throw new F(l);if(!d.c.unlink)throw new F(E.F);if(g.J)throw new F(E.K);try{N.willDeletePath&&
N.willDeletePath(c)}catch(n){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+n.message)}d.c.unlink(d,e);Db(g);try{if(N.onDeletePath)N.onDeletePath(c)}catch(n){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+n.message)}return 0}catch(n){return"undefined"!==typeof FS&&n instanceof F||x(n),-n.h}},___syscall140:function(a,b){R=b;try{var c=W();S();var d=S(),e=S(),g=S();Xb(c,d,g);t[e>>2]=c.position;c.da&&0===d&&0===g&&(c.da=null);return 0}catch(l){return"undefined"!==
typeof FS&&l instanceof F||x(l),-l.h}},___syscall142:function(a,b){R=b;try{var c=S(),d=S(),e=S(),g=S();S();assert(64>=c,"nfds must be less than or equal to 64");assert(!g,"exceptfds not supported");a=0;for(var l=d?t[d>>2]:0,n=d?t[d+4>>2]:0,p=e?t[e>>2]:0,w=e?t[e+4>>2]:0,C=g?t[g>>2]:0,U=g?t[g+4>>2]:0,ca=b=0,V=0,ba=0,P=0,z=0,Ac=(d?t[d>>2]:0)|(e?t[e>>2]:0)|(g?t[g>>2]:0),Bc=(d?t[d+4>>2]:0)|(e?t[e+4>>2]:0)|(g?t[g+4>>2]:0),J=0;J<c;J++){var A=1<<J%32;if(32>J?Ac&A:Bc&A){var Ra=L[J];if(!Ra)throw new F(E.D);
var Sa=5;Ra.f.va&&(Sa=Ra.f.va(Ra));Sa&1&&(32>J?l&A:n&A)&&(32>J?b|=A:ca|=A,a++);Sa&4&&(32>J?p&A:w&A)&&(32>J?V|=A:ba|=A,a++);Sa&2&&(32>J?C&A:U&A)&&(32>J?P|=A:z|=A,a++)}}d&&(t[d>>2]=b,t[d+4>>2]=ca);e&&(t[e>>2]=V,t[e+4>>2]=ba);g&&(t[g>>2]=P,t[g+4>>2]=z);return a}catch(yb){return"undefined"!==typeof FS&&yb instanceof F||x(yb),-yb.h}},___syscall145:function(a,b){R=b;try{var c=W(),d=S();a:{var e=S();for(b=a=0;b<e;b++){var g=t[d+(8*b+4)>>2],l=Yb(c,t[d+8*b>>2],g,void 0);if(0>l){var n=-1;break a}a+=l;if(l<
g)break}n=a}return n}catch(p){return"undefined"!==typeof FS&&p instanceof F||x(p),-p.h}},___syscall146:function(a,b){R=b;try{var c=W(),d=S();a:{var e=S();for(b=a=0;b<e;b++){var g=Zb(c,t[d+8*b>>2],t[d+(8*b+4)>>2],void 0);if(0>g){var l=-1;break a}a+=g}l=a}return l}catch(n){return"undefined"!==typeof FS&&n instanceof F||x(n),-n.h}},___syscall15:function(a,b){R=b;try{var c=T(),d=S(),e;"string"===typeof c?e=O(c,{W:!0}).node:e=c;if(!e.c.m)throw new F(E.F);e.c.m(e,{mode:d&4095|e.mode&-4096,timestamp:Date.now()});
return 0}catch(g){return"undefined"!==typeof FS&&g instanceof F||x(g),-g.h}},___syscall183:function(a,b){R=b;try{var c=S(),d=S();if(0===d)return-E.g;if(d<za("/")+1)return-E.Ca;ya("/",B,c,d);return c}catch(e){return"undefined"!==typeof FS&&e instanceof F||x(e),-e.h}},___syscall195:function(a,b){R=b;try{var c=T(),d=S();return fc(Sb,c,d)}catch(e){return"undefined"!==typeof FS&&e instanceof F||x(e),-e.h}},___syscall196:function(a,b){R=b;try{var c=T(),d=S();return fc(Tb,c,d)}catch(e){return"undefined"!==
typeof FS&&e instanceof F||x(e),-e.h}},___syscall197:function(a,b){R=b;try{var c=W(),d=S();return fc(Sb,c.path,d)}catch(e){return"undefined"!==typeof FS&&e instanceof F||x(e),-e.h}},___syscall221:function(a,b){R=b;try{var c=W();switch(S()){case 0:var d=S();return 0>d?-E.g:Ub(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=S(),c.flags|=d,0;case 12:case 12:return d=S(),Ba[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-E.g;case 9:return ab(E.g),
-1;default:return-E.g}}catch(e){return"undefined"!==typeof FS&&e instanceof F||x(e),-e.h}},___syscall3:function(a,b){R=b;try{var c=W(),d=S(),e=S();return Yb(c,d,e)}catch(g){return"undefined"!==typeof FS&&g instanceof F||x(g),-g.h}},___syscall38:function(a,b){R=b;try{var c=T(),d=T(),e=db(c),g=db(d),l=eb(c),n=eb(d);try{var p=O(c,{parent:!0});var w=p.node;p=O(d,{parent:!0});var C=p.node}catch(z){throw new F(E.K);}if(!w||!C)throw new F(E.A);if(w.l!==C.l)throw new F(E.Da);var U=I(w,l),ca=ib(c,g);if("."!==
ca.charAt(0))throw new F(E.g);ca=ib(d,e);if("."!==ca.charAt(0))throw new F(E.aa);try{var V=I(C,n)}catch(z){}if(U!==V){var ba=H(U.mode),P=Kb(w,l,ba);if(P)throw new F(P);if(P=V?Kb(C,n,ba):Jb(C,n))throw new F(P);if(!w.c.rename)throw new F(E.F);if(U.J||V&&V.J)throw new F(E.K);if(C!==w&&(P=Eb(w,"w")))throw new F(P);try{N.willMovePath&&N.willMovePath(c,d)}catch(z){console.log("FS.trackingDelegate['willMovePath']('"+c+"', '"+d+"') threw an exception: "+z.message)}Db(U);try{w.c.rename(U,C,n)}catch(z){throw z;
}finally{Cb(U)}try{if(N.onMovePath)N.onMovePath(c,d)}catch(z){console.log("FS.trackingDelegate['onMovePath']('"+c+"', '"+d+"') threw an exception: "+z.message)}}return 0}catch(z){return"undefined"!==typeof FS&&z instanceof F||x(z),-z.h}},___syscall4:function(a,b){R=b;try{var c=W(),d=S(),e=S();return Zb(c,d,e)}catch(g){return"undefined"!==typeof FS&&g instanceof F||x(g),-g.h}},___syscall41:function(a,b){R=b;try{var c=W();return Ub(c.path,c.flags,0).fd}catch(d){return"undefined"!==typeof FS&&d instanceof
F||x(d),-d.h}},___syscall42:function(a,b){R=b;try{var c=S();if(0==c)throw new F(E.ya);var d=X.Ga();t[c>>2]=d.La;t[c+4>>2]=d.Qa;return 0}catch(e){return"undefined"!==typeof FS&&e instanceof F||x(e),-e.h}},___syscall5:function(a,b){R=b;try{var c=T(),d=S(),e=S();return Ub(c,d,e).fd}catch(g){return"undefined"!==typeof FS&&g instanceof F||x(g),-g.h}},___syscall54:function(a,b){R=b;try{var c=W(),d=S();switch(d){case 21509:case 21505:return c.tty?0:-E.H;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?
0:-E.H;case 21519:if(!c.tty)return-E.H;var e=S();return t[e>>2]=0;case 21520:return c.tty?-E.g:-E.H;case 21531:a=e=S();if(!c.f.ra)throw new F(E.H);return c.f.ra(c,d,a);case 21523:return c.tty?0:-E.H;case 21524:return c.tty?0:-E.H;default:x("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof FS&&g instanceof F||x(g),-g.h}},___syscall6:function(a,b){R=b;try{var c=W();Wb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof F||x(d),-d.h}},___syscall60:function(a,b){R=b;try{var c=
S();a=ec;ec=c;return a}catch(d){return"undefined"!==typeof FS&&d instanceof F||x(d),-d.h}},___syscall63:function(a,b){R=b;try{var c=W(),d=S();if(c.fd===d)var e=d;else{var g=c.path,l=c.flags,n=L[d];n&&Wb(n);e=Ub(g,l,0,d,d).fd}return e}catch(p){return"undefined"!==typeof FS&&p instanceof F||x(p),-p.h}},___syscall83:function(a,b){R=b;try{var c=T(),d=T();Rb(c,d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof F||x(e),-e.h}},___syscall85:function(a,b){R=b;try{var c=T(),d=S();var e=S();if(0>=
e)var g=-E.g;else{var l=zb(c),n=Math.min(e,za(l)),p=y[d+n];ya(l,B,d,e+1);y[d+n]=p;g=n}return g}catch(w){return"undefined"!==typeof FS&&w instanceof F||x(w),-w.h}},___unlock:function(){},_abort:function(){f.abort()},_emscripten_longjmp:function(a,b){hc(a,b)},_emscripten_memcpy_big:function(a,b,c){B.set(B.subarray(b,b+c),a);return a},_execl:function(){ab(E.Aa);return-1},_exit:function(a){wc(a)},_flock:function(){return 0},_fork:function(){ab(E.S);return-1},_getenv:ic,_getpwnam:function(){throw"getpwnam: TODO";
},_gmtime_r:function(a,b){a=new Date(1E3*t[a>>2]);t[b>>2]=a.getUTCSeconds();t[b+4>>2]=a.getUTCMinutes();t[b+8>>2]=a.getUTCHours();t[b+12>>2]=a.getUTCDate();t[b+16>>2]=a.getUTCMonth();t[b+20>>2]=a.getUTCFullYear()-1900;t[b+24>>2]=a.getUTCDay();t[b+36>>2]=0;t[b+32>>2]=0;t[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;t[b+40>>2]=kc;return b},_llvm_log10_f64:function(){return lc.apply(null,arguments)},_llvm_log2_f64:function(){return mc.apply(null,arguments)},_localtime_r:function(a,
b){nc();a=new Date(1E3*t[a>>2]);t[b>>2]=a.getSeconds();t[b+4>>2]=a.getMinutes();t[b+8>>2]=a.getHours();t[b+12>>2]=a.getDate();t[b+16>>2]=a.getMonth();t[b+20>>2]=a.getFullYear()-1900;t[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);t[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;t[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(2E3,6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;t[b+32>>2]=a;a=t[rc()+(a?4:0)>>2];t[b+40>>2]=a;return b},_longjmp:hc,
_mktime:function(a){nc();var b=new Date(t[a+20>>2]+1900,t[a+16>>2],t[a+12>>2],t[a+8>>2],t[a+4>>2],t[a>>2],0),c=t[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),g=(new Date(2E3,6,1)).getTimezoneOffset(),l=e.getTimezoneOffset(),n=Math.min(l,g);0>c?t[a+32>>2]=Number(g!=l&&n==d):0<c!=(n==d)&&(g=Math.max(l,g),b.setTime(b.getTime()+6E4*((0<c?n:g)-d)));t[a+24>>2]=b.getDay();t[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;return b.getTime()/1E3|0},_pthread_getspecific:function(a){return sc[a]||
0},_pthread_key_create:function(a){if(0==a)return E.g;t[a>>2]=tc;sc[tc]=0;tc++;return 0},_pthread_once:uc,_pthread_setspecific:function(a,b){if(!(a in sc))return E.g;sc[a]=b;return 0},_time:function(a){var b=Date.now()/1E3|0;a&&(t[a>>2]=b);return b},_timespec_get:function(a,b){if(1!==b)return ab(E.g),0;var c=Date.now();t[a>>2]=c/1E3|0;t[a+4>>2]=c%1E3*1E6|0;return b},_waitpid:function(){return vc.apply(null,arguments)},DYNAMICTOP_PTR:u,STACKTOP:Ga};var xc=f.asm(f.Ea,f.Fa,buffer);f.asm=xc;
f.___cxa_demangle=function(){return f.asm.___cxa_demangle.apply(null,arguments)};var Ya=f.___emscripten_environ_constructor=function(){return f.asm.___emscripten_environ_constructor.apply(null,arguments)};f.___errno_location=function(){return f.asm.___errno_location.apply(null,arguments)};
var qc=f.__get_daylight=function(){return f.asm.__get_daylight.apply(null,arguments)},pc=f.__get_timezone=function(){return f.asm.__get_timezone.apply(null,arguments)},rc=f.__get_tzname=function(){return f.asm.__get_tzname.apply(null,arguments)},jc=f._free=function(){return f.asm._free.apply(null,arguments)};f._main=function(){return f.asm._main.apply(null,arguments)};var ta=f._malloc=function(){return f.asm._malloc.apply(null,arguments)};f.setThrew=function(){return f.asm.setThrew.apply(null,arguments)};
var ua=f.stackAlloc=function(){return f.asm.stackAlloc.apply(null,arguments)},Z=f.stackRestore=function(){return f.asm.stackRestore.apply(null,arguments)},Y=f.stackSave=function(){return f.asm.stackSave.apply(null,arguments)};f.dynCall_ii=function(){return f.asm.dynCall_ii.apply(null,arguments)};f.dynCall_iii=function(){return f.asm.dynCall_iii.apply(null,arguments)};f.dynCall_iiii=function(){return f.asm.dynCall_iiii.apply(null,arguments)};
f.dynCall_iiiii=function(){return f.asm.dynCall_iiiii.apply(null,arguments)};f.dynCall_v=function(){return f.asm.dynCall_v.apply(null,arguments)};f.dynCall_vi=function(){return f.asm.dynCall_vi.apply(null,arguments)};f.dynCall_vii=function(){return f.asm.dynCall_vii.apply(null,arguments)};f.dynCall_viii=function(){return f.asm.dynCall_viii.apply(null,arguments)};f.dynCall_viiii=function(){return f.asm.dynCall_viiii.apply(null,arguments)};
f.dynCall_viiiii=function(){return f.asm.dynCall_viiiii.apply(null,arguments)};f.dynCall_viiiiii=function(){return f.asm.dynCall_viiiiii.apply(null,arguments)};f.dynCall_viiiiiii=function(){return f.asm.dynCall_viiiiiii.apply(null,arguments)};f.asm=xc;function ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ka.prototype=Error();ka.prototype.constructor=ka;var yc;Wa=function zc(){f.calledRun||Cc();f.calledRun||(Wa=zc)};
f.callMain=function(a){a=a||[];Qa||(Qa=!0,Ka(Ma));var b=a.length+1,c=ua(4*(b+1));t[c>>2]=Aa(f.thisProgram);for(var d=1;d<b;d++)t[(c>>2)+d]=Aa(a[d-1]);t[(c>>2)+b]=0;try{var e=f._main(b,c,0);wc(e,!0)}catch(g){g instanceof ka||("SimulateInfiniteLoop"==g?f.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),q("exception thrown: "+a),f.quit(1,g)))}finally{}};
function Cc(a){function b(){if(!f.calledRun&&(f.calledRun=!0,!ra)){Qa||(Qa=!0,Ka(Ma));Ka(Na);if(f.onRuntimeInitialized)f.onRuntimeInitialized();f._main&&Dc&&f.callMain(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Pa.unshift(b)}Ka(Pa)}}a=a||f.arguments;if(!(0<Ua)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ta();Ka(La);0<Ua||f.calledRun||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},
1);b()},1)):b())}}f.run=Cc;function wc(a,b){if(!b||!f.noExitRuntime||0!==a){if(!f.noExitRuntime&&(ra=!0,Ga=yc,Ka(Oa),f.onExit))f.onExit(a);f.quit(a,new ka(a))}}function x(a){if(f.onAbort)f.onAbort(a);void 0!==a?(la(a),q(a),a=JSON.stringify(a)):a="";ra=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}f.abort=x;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Dc=!0;f.noInitialRun&&(Dc=!1);f.noExitRuntime=!0;Cc();
